### ISSUE TITLE
Naive Implementation - Fixed Domain

### ISSUE THREAD

**Issue by KikeM** [KikeM/msc-thesis#14]
The goal is to build a simple code base that solves the reduction problem completely for a fixed domain.

Is this naive approach, **the Discrete Empirical Interpolation is not used**, since it would only add extra layers of complexity.
The ROM operators are obtained by assembly and projection of the FOM operators. 

I am aware this does not honor the offline-online split principle, but it does allow me to tackle all the implementation details. 
Once these are dealt with, implementing the (M)DEIM algorithms should not be too cumbersome.  

## Steps

- [x] Definition of Manufactured Solution #10.
- [x] Parametrized FOM Solver #7 #2 #9 https://github.com/KikeM/msc-thesis/issues/15.
- [x] Basis construction: ~~POD~~ SVD orthogonalisation #4 #5.
- [x] Parametrized ROM Solver #8 #6.
