### ISSUE TITLE
DISC : From Naive To ... ?

### ISSUE THREAD

**Issue by KikeM** [KikeM/msc-thesis#21]
Now that I have the naive ROM implementation put up for a fixed domain, the questions arises on which task to tackle next.

We have the following unresolved issues, ordered from complex to simple:

- [ ] Moving Domain: Mesh Deformation.
- [ ] (M)DEIM Implementation. 
- [ ] POD Implementation (#5).
- [ ] Moving Domain: Generalised Transformation.
- [ ] ROM-community error calculations (#20).

**Comment by KikeM** [comment]
> 2. Regarding the second issue, fenics has an ALE.move() method which allegedly displaces the mesh.
> However, I am skeptical it will be easy and straightforward.

I accidentally discovered the `mesh.scale` method, which I think it should be the one I ought to use.

**Comment by KikeM** [comment]
> 1. The very first issue is the one where I feel the most uncertain about.

Implementing DEIM was not too difficult once I wrapped my head around the DOFs mapping (although I haven't tested it for P2 😅).
Let's see how we fare with MDEIM.

**Comment by KikeM** [comment]
For the time being, I choose not to solve the problem with the generalized transformation. 

We can simply comment on it in the body of the thesis, but if we can show good convergence for the solutions in the physical domain there is no need to do it in the reference domain too.
