### ISSUE TITLE
Road to Graduation

### ISSUE THREAD

**Issue by emvalbuena** [KikeM/msc-thesis#87]
## Preparation greenlight review

- Around 6 weeks before you are finished with you thesis, you should apply for the greenlight review to get permission to defend.
- [x] #83 
To apply for the greenlight review fill out the AE-3a form.
- [ ] #84 
To avoid plagiarism you are required to upload your draft thesis in the Turnitin assignment page “Thesis plagiarism Checker” in the Brightspace page Master Thesis AE and provide the daily supervisor with a pdf print out of the Turnitin original report.
- [x] #85 
Fill-in and send to Steven. 

### Deliverables
1 week before the greenlight meeting:
- Draft thesis;
- Turnitin report.  

--- 

## **Apply for your diploma**

- [ ] https://github.com/KikeM/msc-thesis/issues/88 
**No later than 20 working days** prior to your intended defence and Graduation date you should apply for your diploma by filling out the form [Msc diploma application form AE-3b](https://www.tudelft.nl/studenten/faculteiten/lr-studentenportal/onderwijs/education/forms)' and send this to the SPA-E&SA (<spa-lr@tudelft.nl>).
- [ ] https://github.com/KikeM/msc-thesis/issues/91 
You also will have to define the Graduation date and time with the secretary of the Chair of the Assessment committee *no later than 20 working days prior to your Graduation date*.
- https://github.com/KikeM/msc-thesis/issues/89 With the [Room reservation form AE-3c](https://www.tudelft.nl/studenten/faculteiten/lr-studentenportal/onderwijs/education/forms) you can arrange via the Service desk AE a room for the presentation and one for the Graduation Ceremony. The presentation will be approximately 1 hour, Defence and assessment will take approximately 1 hour depending on the Assessment Committee, the Graduation Ceremony  takes approximately ½ an hour.
- [ ] #90 
The Service desk AE confirms the reservation date, time and locations to the secretary of the assessment committee and the student. This confirmation together with the students name, track, thesis title and abstract, amount of attendants and contact person/phone number for the Graduation day will also be send to <education-AE@tudelft.nl> and to communications for the announcement on the website.
- [ ] The SPA-E&SA will check whether you comply with the requirements, i.e. if you have completed all your courses and whether your committee complies with the regulations.  If not, you will be informed by email. You have to comply with all requirements *at least 5 working days before the Graduation date*.
- [ ] https://github.com/KikeM/msc-thesis/issues/92 
All students are also required to upload  their final Master Thesis (final version) in the same Turnitin assignment page before Graduation and provide the daily supervisor with a print out of the Turnitin originality report of the final Thesis. 
-  No later than 5 working days before the Graduation date you have provided all members of the assessment committee with:
    - [ ] a printed version of the Thesis to be defended;
    - [ ] an upload of the Thesis to be defended in the [Turnitin assignment page](https://brightspace.tudelft.nl/d2l/le/content/43776/Home) in the Brighspace page 'Master Thesis AE'.
    - [ ] a print-out of the originality report (following the check by the supervisor).
    - Note 1: Digital copies are allowed in consultation with your supervisor/committee.
    - Note 2: Some departments require the reports 10 working days before Graduation, so always keep yourself informed about the rules within your department of graduation.
- [ ] The daily supervisor checks the Originality Report. In case of omissions or if the upload has not taken place the defence and Graduation is postponed and/or cancelled.
-  [ ] If you comply with the requirements, the SPA-E&SA will acknowledge the received application and will send an email to both the student and the secretary of the chairperson of the assessment committee confirming the date of Graduation.
- [ ] The SPA-E&SA will subsequently send an email to the chairperson of the assessment committee (cc. secretary) in which the date of the final presentation is stated and a copy of the Assessment form and Rubrics form can be found.
- [ ] https://github.com/KikeM/msc-thesis/issues/93 
If you didn't receive your diploma at this ceremony you have to collect your diploma at our administration. For this you need to make an appointment using the following email address: [SPA-LR@tudelft.nl](mailto:OSA-LR@tudelft.nl). Due to legislation your diploma cannot be send by post.
